# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [2]:
import pandas as pd
a = {"name":["raj","ram","raju","rahul","rohan"],
     "age":[22,33,42,54,11],
     "score":[33,44,55,66,77]
}

b = pd.DataFrame(a)

# select single
b[b['score']>45]

#selecting multiple condition (AND)
b[(b["age"]> 33)& (b['score']>45)]

#selecting multiple condition (or)
b[(b["age"]> 33) | (b['score']>45)]

#selecting multiple condition (NOT)
b[~(b["score"]> 50)]

b[(b["age"]> 30) & (b["score"]>40)]

    name  age  score
1    ram   33     44
2   raju   42     55
3  rahul   54     66

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [6]:
#1 age > 25 AND score > 40
import pandas as pd
a = {"name":["raj","ram","raju","rahul","rohan"],
     "age":[22,33,42,54,11],
     "score":[33,44,55,66,77]
}

b = pd.DataFrame(a)
b[(b['age']> 25) & (b['score']>40)]

#2 age > 35 OR score >= 40
b[(b['age']> 25) | (b['score']>40)]

#3 age between 25 AND 45(inclusive)
b[(b['age']>=25) & (b["age"]<= 45)]

   name  age  score
1   ram   33     44
2  raju   42     55

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
# Simple query : Age > 25
print(b)
print(b.query('age > 25'))

# multiple conditions using query
print(b.query('age < 35 and score >= 60'))

print(b.query('age >= 30 and score >= 90'))

# Thershold means (@)
score = 70   
b.query("score>= @score")

    name  age  score
0    raj   22     33
1    ram   33     44
2   raju   42     55
3  rahul   54     66
4  rohan   11     77
    name  age  score
1    ram   33     44
2   raju   42     55
3  rahul   54     66
    name  age  score
4  rohan   11     77
Empty DataFrame
Columns: [name, age, score]
Index: []

    name  age  score
4  rohan   11     77

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [5]:
print(b)
# 1 convert name to upper case
print(b['name'].str.upper())

 #  2 title() capitalise first letter of the words
print(b['name'].str.title())

 # replace a substring(oldstring replace to newstring)
b['name'].str.replace('ram','Sham')

 # check if name column contains tha letter a
b[b['name'].str.contains('r')]

 # starswith and endswith
b[b['name'].str.startswith("d")]

b[b['name'].str.endswith("s")]

    name  age  score
0    raj   22     33
1    ram   33     44
2   raju   42     55
3  rahul   54     66
4  rohan   11     77
0      RAJ
1      RAM
2     RAJU
3    RAHUL
4    ROHAN
Name: name, dtype: object
0      Raj
1      Ram
2     Raju
3    Rahul
4    Rohan
Name: name, dtype: object

Empty DataFrame
Columns: [name, age, score]
Index: []

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [22]:
import pandas as pd
data = {
    "Name":["Rishi", "raj", "rahul","Rishu"],
    "Age":[23,24,25,26],
    "Salary":[90000,980000,800000,70989]
}
df = pd.DataFrame(data)
df
# 1. Build a DataFrame with columns: Name, Age, City, Score
import pandas as pd
data = {
    "Name":["Rishi", "raj", "rahul","Rishu"],
    "Age":[29,21,45,27],
    "City":["Mumbai", "Delhi", "Bihar","Punjab"],
    "Score":[90,97,34,66]

}
df = pd.DataFrame(data)
df
# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

print(df[df["Age"]>25])

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here
print(df[df["City"].isin(["Delhi", "Mumbai"])])

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here
print(df.query("Score >= 85 and Age < 35"))


# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here
df["City"].str.lower()
df["City"].str.replace("Delhi", "New Delhi")

    Name  Age    City  Score
0  Rishi   29  Mumbai     90
2  rahul   45   Bihar     34
3  Rishu   27  Punjab     66
    Name  Age    City  Score
0  Rishi   29  Mumbai     90
1    raj   21   Delhi     97
    Name  Age    City  Score
0  Rishi   29  Mumbai     90
1    raj   21   Delhi     97

0       Mumbai
1    New Delhi
2        Bihar
3       Punjab
Name: City, dtype: object

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.