# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [1]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [2]:
avg_salary = df.groupby('Department')['Salary'].mean()
print("\nAverage Salary by Department:")
print(avg_salary)

Average Salary by Department:
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [3]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [4]:
avg_age = df.groupby('Department')['Age'].mean()
print(avg_age)

print(df.groupby('Department').agg({'Salary':['mean','max','max'],
                                    'Age':['min','max']}))

Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64
                  Salary               Age
                    mean    max    max min max
Department
Finance     61000.000000  65000  65000  26  35
HR          51000.000000  52000  52000  28  29
IT          72333.333333  75000  75000  30  32

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [5]:
df.pivot_table(index='Department', values='Salary', aggfunc='mean')
df.pivot_table(index='Department', values=['Salary','Age'], aggfunc='mean')

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [6]:
# age group -> 21-25,25-30,31-35
df['Age_group'] = pd.cut(df['Age'],bins=[25,30,35,40],labels=['25-30','31-35','36-40'])
pd.crosstab(df['Department'],df['Age_group'])

Age_group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

In [7]:
# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

import pandas as pd
d=({
    'Department':['HR','IT','IT','Finance','Finance','HR'],
    'Employee':['John','Sarah','Mike','Anna','Steve','Kate'],
    'Salary':[50000,70000,72000,52000,75000,58000],
    'Age':[28,32,30,27,35,29],
    'City':['New York','San Francisco','San Francisco','New York','San Francisco','London']
})
df=pd.DataFrame(d)
print(df)

  Department Employee  Salary  Age           City
0         HR     John   50000   28       New York
1         IT    Sarah   70000   32  San Francisco
2         IT     Mike   72000   30  San Francisco
3    Finance     Anna   52000   27       New York
4    Finance    Steve   75000   35  San Francisco
5         HR     Kate   58000   29         London

In [8]:
#2. Group by Department to get average Salary and max Age
result = df.groupby('Department').agg(avg_salary=('Salary','mean'),max_age=('Age','max'))
print(result)

            avg_salary  max_age
Department
Finance        63500.0       35
HR             54000.0       29
IT             71000.0       32

In [9]:
result2 = df.groupby('Department').agg(
    avg_salary=('Salary','mean'),
    max_age=('Age','max'),
    min_salary=('Salary','min'),
    emp_count=('Employee','count')
    )
print(result2)

            avg_salary  max_age  min_salary  emp_count
Department
Finance        63500.0       35       52000          2
HR             54000.0       29       50000          2
IT             71000.0       32       70000          2

In [10]:

# 4. Create a pivot_table to see mean Salary by Department and City
pivot = pd.pivot_table(df,values='Salary',index='Department',columns='City',aggfunc='mean')
print(pivot)

City         London  New York  San Francisco
Department
Finance         NaN   52000.0        75000.0
HR          58000.0   50000.0            NaN
IT              NaN       NaN        71000.0

In [11]:

# 5. Build a crosstab for Department vs City
# Write your code here
crosstab = pd.crosstab(df['Department'],df['City'])
print(crosstab)

City        London  New York  San Francisco
Department
Finance          0         1              1
HR               1         1              0
IT               0         0              2

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.