# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [1]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}
df= pd.DataFrame(data)
df.info()
df['OrderDate']=pd.to_datetime(df['OrderDate'],format='mixed',errors='coerce')
print(df)

df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce', format='mixed').dt.strftime('%d-%m-%y')
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   OrderDate  5 non-null      object
 2   Customer   5 non-null      object
 3   Amount     5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

   OrderID OrderDate Customer  Amount
0     1001  05-01-24    Alice     250
1     1002  12-01-24      Bob     400
2     1003  15-01-24  Charlie     150
3     1004  20-01-24    David     300
4     1005  25-01-24     Emma     500

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [2]:

import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}
df= pd.DataFrame(data)
df

df_idx = df.set_index("OrderDate")
df_idx

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
2024/01/12     1002      Bob     400
15-01-2024     1003  Charlie     150
2024-01-20     1004    David     300
20240125       1005     Emma     500

In [3]:
df_idx.index = pd.to_datetime(df_idx.index, format='mixed', errors='coerce')
monthly_Amount = df_idx.resample("ME")["Amount"].sum()
monthly_Amount

OrderDate
2024-01-31    1600
Freq: ME, Name: Amount, dtype: int64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [4]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

import pandas as pd

data = {
    "VisitDate": [
        "2026-01-01",
        "2026-01-02",
        "2026-01-03",

    ],
    "Visits": [120,  180, 240]
}

df = pd.DataFrame(data)
df

#2️⃣ Convert  visitdate to datetime
print(df["VisitDate"])
df["VisitDate"] = pd.to_datetime(df["VisitDate"])
print(df["VisitDate"].dtype)

# 3️⃣ Set VisitDate as the index
# Write your code here
df["VisitDate"] = pd.to_datetime(df["VisitDate"])

df = df.set_index("VisitDate")
print(df)

print(df.index)


# 4️⃣ Resample to get total visitors per month
# Write your code here
monthly_visits = df.resample("ME").sum()
print(monthly_visits)


# 5️⃣ Resample to get average visitors per week
# Write your code here
weekly_avg_visits = df.resample("W").mean()
print(weekly_avg_visits)

0    2026-01-01
1    2026-01-02
2    2026-01-03
Name: VisitDate, dtype: object
datetime64[ns]
            Visits
VisitDate
2026-01-01     120
2026-01-02     180
2026-01-03     240
DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03'], dtype='datetime64[ns]', name='VisitDate', freq=None)
            Visits
VisitDate
2026-01-31     540
            Visits
VisitDate
2026-01-04   180.0

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.